## helm3 template --set global.env=oman,global.mode.standard=false,global.namespace.prefix=oman,global.namespace.mid=fluxble,global.host.prefix=oman,global.host.baseUrl=fluxble.com ./
global:

  nsPrefix: dev-meeraspace

  baseUrl: dev.meeraspace.com
  
  gateway: default/gateway


# fullnameOverride: 

replicaCount: 1

envs:
  enabled: false

job:
  initdb:
    enabled: false

image:
  repository: registry.gitlab.com/target-digital-transformation/environment-store/master
  tag: "latest"  
  # repository: registry.tespkg.in/library/envs
  # tag: "alpine3.10"  
  pullPolicy: Always
  # pullPolicy: IfNotPresent
  ports:
  - name: envs
    containerPort: 9112
    protocol: TCP
  extraCommand:
  - /usr/local/envs/bin/envs
  - serve
  - --address=:9112
  - --schema=$(schema)  
  - --host=$(envsHost)
  - --dsn=http://$(consulHTTPAddr)/$(dbname)
  - --asset-dir=/usr/local/envs/static
  extraEnv:
    dbname: envs
    schema: https
  extraENVRulehandled:
    envsHost: envs.$baseUrl
    consulHTTPAddr: consul.$nsPrefix-consul:8500


service:
  type: ClusterIP
  ports:
  - port: 9112
    name: envs
    targetPort: 9112

istio:
  envoyfilter:
    enabled: false

  virtualservice:
    enabled: true
    host: envs
    http:
    - route:
      - destination:
          host: envs
          port:
            number: 9112

  virtualserviceGrpcMtls:
    enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts:
  ## If true,  Pod volumes to mount into the container's filesystem
  # enabled: true
  enabled: false
  volumeMounts:

volumes:
  enabled: false
  ## if type is configmap, will auto use the configmap value by  `name: {{ template "APP.fullname" . }}-config`
  configmap:
    enabled: false
  volumes:

persistentVolumeClaim1:
  ## If true,  will create/use a Persistent Volume Claim
  enabled: false
  # enabled: true
  name: CHANGEME   # same to volumes.volumes.volumesvolumes.claimName
  ## supported values: "ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce"
  accessModes:
    - ReadWriteOnce
  annotations: {}
  # existingClaim: ""
  size: 4Gi
  storageClass: "standard"

configmap:
  enabled: false

  configurationEnv:
    {}