global:
  env: energy
  mode: 
    standard: true
    ## If set to "true"，  no namespace.prefix & host.prefix spec
  namespace:
    prefix: energy 
    mid: fluxble
  host:
    prefix: energy
    baseUrl: fluxble.com
  service:
    gateway:
      name: gateway
      namespace: default

# fullnameOverride: 

replicaCount: 1

configmapEnvVars:
  enabled: false

image:
  repository: registry.tespkg.in/library/envs
  tag: "alpine3.10"  
  pullPolicy: Always
  # pullPolicy: IfNotPresent
  ports:
  - name: envs
    containerPort: 9112
    protocol: TCP
  extraCommand:
  - /usr/local/envs/bin/envs
  - serve
  - --address=:9112
  - --schema=https  
  - --host=$(envsHost)
  - --dsn=http://consul.global-fluxble-consul:8500/envsenergy
  - --dsn=http://consul.global-fluxble-consul:8500/envstarget
  - --asset-dir=/usr/local/envs/static

  extraENVRulehandled:
    envsHost: envs.$hostPrefix.$baseUrl
    # consulHTTPAddr: consul.$nsPrefix-$nsMid-consul:8500

  ## ExtraEnv has the highest priority when there are multiple repeating envs
  extraEnv:

service:
  type: ClusterIP
  ports:
  - port: 9112
    name: envs
    targetPort: 9112

istio:
  envoyfilter:
    enabled: false

  virtualservice:
    enabled: true
    host: envs
    http:
    - route:
      - destination:
          host: envs
          port:
            number: 9112

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

volumeMounts:
## If true,  Pod volumes to mount into the container's filesystem
  enabled: false

volumes:
## If true, will create/use a Volume, configmap nfs hostPath emptyDir
  enabled: false


persistentVolumeClaim1:
## If true,  will create/use a Persistent Volume Claim
  enabled: false

configmap:
  enabled: false