services:
  - name: gcr.io/etcd-development/etcd:v3.3.13
    alias: etcd
    command: ["/usr/local/bin/etcd", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://0.0.0.0:2379"]
  - name: consul
    command: ["consul", "agent", "-client=0.0.0.0", "-dev"]

variables:
  APP_CHART_NAME: envs ## replace the right chart name
  RELEASE_NAME: envs
  KUBECONFIG: /etc/deploy/config
  SLACK_CHANNEL: gitlab-notifications
  DOCKER_DRIVER: overlay2

stages:
  - unit-test
  - test
  - build
  - deploy_to_dev
  - push_incubator_chart
  - deploy_to_test
  - push_stable_chart
  - release_request
  - deploy_to_staging
  - deploy_to_demo
  - deploy_to_prod

include:
  - remote: https://target-digital-transformation.gitlab.io/pipeline/01_build_reuse_image.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/02_v2_deploy_to_dev.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/03_v2_push_Incubator_chart.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/04_v2_deploy_to_test.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/05_v2_push_stable_chart.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/06_v2_release_request.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_staging.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_prod_odp_azure.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_prod_eks_fluxble.yml

test-coverage:
  image: golang:1.13
  stage: unit-test
  before_script:
    - export PATH=$PATH:$GOPATH/bin
    - export ETCD_DSN=etcd://etcd:2379/a/bc
    - export CONSUL_DSN=http://consul:8500/a/bc
    - |
      if ( echo ${CI_RUNNER_TAGS} | grep -q kubernetes ); then
        export DOCKER_HOST="tcp://localhost:2375"
        export ETCD_DSN=etcd://localhost:2379/a/bc
        export CONSUL_DSN=http://localhost:8500/a/bc
      fi  
  script:
    - make run-test

build_enva:
  image: docker:18.09
  stage: build
  services:
    - docker:18.09-dind
  before_script:
    - apk add bash make
    - if ( echo ${CI_RUNNER_TAGS} | grep -q docker-in-docker );then export DOCKER_HOST="tcp://localhost:2375";else echo "nothing to do";fi
    - docker login -u gitlab-ci -p $DOCKER_REGISTRY_TESPKG_PASSWORD registry.tespkg.in 
  script:
    make PUSH=true build-images
  only:
    - master
    - tags
  when: manual

build_image_envs:
  extends: .build_single_image
  stage: build
  only:
    - master
    - tags

dev.meeraspace.com:
  extends: .deploy_to_dev_v2
  variables:
    ##   helm3 install [RELEASE_NAME] [APP_CHART_NAME] -n [NAMESPACE] --set global.env=${environment_name}
    NAMESPACE: dev-meeraspace-envs
    environment_name: dev
    environment_url: https://dev.meeraspace.com
    nsPrefix: dev-meeraspace
    baseUrl: dev.meeraspace.com
    gateway: default/gateway
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.repository=$CI_REGISTRY_IMAGE/${CI_COMMIT_REF_SLUG} \
        --set-string image.tag=${CI_COMMIT_SHA:0:8} \
        --debug --wait ./     
  only:
    - master

push_incubator_chart:
  extends: .push_incubator_chart_v2

test.meeraspace.com:
  extends: .deploy_to_test_v2
  variables:
    NAMESPACE: test-meeraspace-envs
    environment_name: test
    environment_url: https://test.meeraspace.com
    nsPrefix: test-meeraspace
    baseUrl: test.meeraspace.com
    gateway: default/gateway
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --debug --wait ./    

kenya.meeraspace.com:
  extends: .deploy_to_test_v2
  variables:
    NAMESPACE: kenya-meeraspace-envs
    environment_name: kenya
    environment_url: https://kenya.meeraspace.com
  when: manual

push_stable_chart:
  extends: .push_stable_chart_v2

request_to_internal.meeraspace.com:
  extends: .release_request_v2
  variables: 
    environment_url: https://internal.meeraspace.com
    SLACK_CHANNEL: release-notifications


internal.meeraspace.com:
  extends: .deploy_to_staging_v2
  variables:
    NAMESPACE: internal-meeraspace-envs
    environment_name: internal
    environment_url: https://internal.meeraspace.com
    SLACK_CHANNEL: release-notifications
    nsPrefix: internal-meeraspace
    baseUrl: internal.meeraspace.com
    gateway: default/gateway
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --debug --wait ./      
  when: manual

energy.fluxble.com:
  extends: .deploy_to_staging_v2
  variables:
    NAMESPACE: energy-fluxble-envs
    environment_name: energy
    environment_url: https://energy.fluxble.com
    SLACK_CHANNEL: release-notifications
    nsPrefix: energy-fluxble
    baseUrl: energy.fluxble.com
    gateway: default/gateway
    consulHTTPAddr: consul.global-fluxble-consul:8500
    dbname: envsenergy
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.extraEnv.dbname=${dbname} \
        --set image.extraENVRulehandled.consulHTTPAddr=${consulHTTPAddr} \
        --debug --wait ./      
  when: manual

target.fluxble.com:
  extends: .deploy_to_staging_v2
  variables:
    NAMESPACE: target-fluxble-envs
    environment_name: target
    environment_url: https://target.fluxble.com
    SLACK_CHANNEL: release-notifications
    nsPrefix: target-fluxble
    baseUrl: target.fluxble.com
    gateway: default/gateway
    consulHTTPAddr: consul.global-fluxble-consul:8500
    dbname: envstarget
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.extraEnv.dbname=${dbname} \
        --set image.extraENVRulehandled.consulHTTPAddr=${consulHTTPAddr} \
        --debug --wait ./      
  when: manual

global.fluxble.com:
  extends: .deploy_to_staging_v2
  variables:
    NAMESPACE: global-fluxble-envs
    environment_name: global
    environment_url: https://global.fluxble.com
    SLACK_CHANNEL: release-notifications
    nsPrefix: global-fluxble
    baseUrl: fluxble.com
    gateway: istio-system/global-gateway
    consulHTTPAddr: consul.global-fluxble-consul:8500
    dbname: envs
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.extraEnv.dbname=${dbname} \
        --set image.extraENVRulehandled.consulHTTPAddr=${consulHTTPAddr} \
        --debug --wait ./      
  when: manual

oman.fluxble.com:
  stage: deploy_to_prod
  extends: .deploy_to_prod_odp_azure
  variables:
    NAMESPACE: oman-fluxble-envs
    environment_name: oman
    environment_url: https://oman.fluxble.com
    SLACK_CHANNEL: gitlab-test
    nsPrefix: oman-fluxble
    baseUrl: oman.fluxble.com
    gateway: istio-system/global-gateway
    consulHTTPAddr: consul.oman-fluxble-consul:8500
    dbname: envs    
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --debug --wait ./

omangov.fluxble.com:
  stage: deploy_to_prod
  extends: .deploy_to_prod_odp_azure
  variables:
    NAMESPACE: omangov-fluxble-envs
    environment_name: omangov
    environment_url: https://omangov.fluxble.com
    SLACK_CHANNEL: gitlab-test
    nsPrefix: omangov-fluxble
    baseUrl: omangov.fluxble.com
    gateway: istio-system/global-gateway
    consulHTTPAddr: consul.oman-fluxble-consul:8500
    dbname: envs       
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --debug --wait ./