services:
  - name: gcr.io/etcd-development/etcd:v3.3.13
    alias: etcd
    command: ["/usr/local/bin/etcd", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://0.0.0.0:2379"]
  - name: consul
    command: ["consul", "agent", "-client=0.0.0.0", "-dev"]

variables:
  APP_CHART_NAME: envs ## replace the right chart name
  RELEASE_NAME: envs
  KUBECONFIG: /etc/deploy/config
  SLACK_CHANNEL: gitlab-notifications
  DOCKER_DRIVER: overlay2
  manifests_ci_token: $manifests_ci_token_envs
  manifests_repo: gitlab.com/target-digital-transformation/devops-group/manifests/general/envs.git

stages:
  - unit-test
  - test
  - build
  - deploy_to_dev
  - push_incubator_chart
  - deploy_to_test
  - push_stable_chart
  - release_request
  - deploy_to_staging
  - deploy_to_demo
  - deploy_to_prod

include:
  - remote: https://target-digital-transformation.gitlab.io/pipeline/01_build_reuse_image.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/02_v2_deploy_to_dev.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/03_v2_push_Incubator_chart.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/04_v2_deploy_to_test.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/05_v2_push_stable_chart.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/06_v2_release_request.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_staging.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_prod_odp_azure.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_prod_eks_fluxble.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/02_v3_deploy_to_dev_via_argocd.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/04_v3_deploy_to_test_via_argocd.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/07_v3_deploy_to_prod_via_argocd.yml

test-coverage:
  image: golang:1.13
  stage: unit-test
  before_script:
    - export PATH=$PATH:$GOPATH/bin
    - export ETCD_DSN=etcd://etcd:2379/a/bc
    - export CONSUL_DSN=http://consul:8500/a/bc
    - |
      if ( echo ${CI_RUNNER_TAGS} | grep -q kubernetes ); then
        export DOCKER_HOST="tcp://localhost:2375"
        export ETCD_DSN=etcd://localhost:2379/a/bc
        export CONSUL_DSN=http://localhost:8500/a/bc
      fi  
  script:
    - make run-test

build_enva:
  image: docker:18.09
  stage: build
  services:
    - docker:18.09-dind
  before_script:
    - apk add bash make
    - if ( echo ${CI_RUNNER_TAGS} | grep -q docker-in-docker );then export DOCKER_HOST="tcp://localhost:2375";else echo "nothing to do";fi
    - docker login -u tespkg -p $DOCKER_REGISTRY_TESPKG_PASSWORD registry.tespkg.in 
  script:
    make PUSH=true build-images
  only:
    - master
    - tags
  when: manual
  tags:
    - woking-physical

build_image_envs:
  extends: .build_single_image
  stage: build
  only:
    - master
    - tags

0-0-dev-gke-dev:
  interruptible: true
  extends: .deploy_to_dev_v3_via_argocd

0-0-dev-gke-dev2:
  interruptible: true
  extends: .deploy_to_dev_v3_via_argocd
  
1-0-test-gke-test:
  interruptible: true
  extends: .deploy_to_test_v3_via_argocd

1-0-test-gke-test2:
  interruptible: true
  extends: .deploy_to_test_v3_via_argocd

#4-0-prod-eks-fluxble-target  it will use values-target.yaml to deploy
4-0-prod-eks-fluxble-target:
  stage: deploy_to_prod
  interruptible: true
  extends: .deploy_to_prod_v3_via_argocd

4-0-prod-eks-fluxble-workspace:
  stage: deploy_to_prod
  interruptible: true
  extends: .deploy_to_prod_v3_via_argocd

4-0-prod-eks-fluxble-energy:
  stage: deploy_to_prod
  interruptible: true
  extends: .deploy_to_prod_v3_via_argocd


kenya.meeraspace.com:
  extends: .deploy_to_test_v2
  variables:
    NAMESPACE: kenya-meeraspace-envs
    environment_name: kenya
    environment_url: https://kenya.meeraspace.com
  when: manual

push_stable_chart:
  extends: .push_stable_chart_v2

request_to_internal.meeraspace.com:
  extends: .release_request_v2
  variables: 
    environment_url: https://internal.meeraspace.com
    SLACK_CHANNEL: release-notifications


energy.fluxble.com:
  extends: .deploy_to_staging_v2
  variables:
    NAMESPACE: energy-fluxble-envs
    environment_name: energy
    environment_url: https://energy.fluxble.com
    SLACK_CHANNEL: release-notifications
    nsPrefix: energy-fluxble
    baseUrl: energy.fluxble.com
    gateway: default/gateway
    consulHTTPAddr: consul.global-fluxble-consul:8500
    dbname: envsenergy
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.extraEnv.dbname=${dbname} \
        --set image.extraENVRulehandled.consulHTTPAddr=${consulHTTPAddr} \
        --debug --wait ./      
  when: manual


global.fluxble.com:
  extends: .deploy_to_staging_v2
  variables:
    NAMESPACE: global-fluxble-envs
    environment_name: global
    environment_url: https://global.fluxble.com
    SLACK_CHANNEL: release-notifications
    nsPrefix: global-fluxble
    baseUrl: fluxble.com
    gateway: istio-system/global-gateway
    consulHTTPAddr: consul.global-fluxble-consul:8500
    dbname: envs
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.extraEnv.dbname=${dbname} \
        --set image.extraENVRulehandled.consulHTTPAddr=${consulHTTPAddr} \
        --debug --wait ./      
  when: manual

oman.fluxble.com:
  stage: deploy_to_prod
  extends: .deploy_to_prod_odp_azure
  variables:
    NAMESPACE: oman-fluxble-envs
    environment_name: oman
    environment_url: https://oman.fluxble.com
    SLACK_CHANNEL: gitlab-test
    nsPrefix: oman-fluxble
    baseUrl: oman.fluxble.com
    gateway: istio-system/global-gateway
    consulHTTPAddr: consul.oman-fluxble-consul:8500
    dbname: envs    
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --debug --wait ./

omangov.fluxble.com:
  stage: deploy_to_prod
  extends: .deploy_to_prod_odp_azure
  variables:
    NAMESPACE: omangov-fluxble-envs
    environment_name: omangov
    environment_url: https://omangov.fluxble.com
    SLACK_CHANNEL: gitlab-test
    nsPrefix: omangov-fluxble
    baseUrl: omangov.fluxble.com
    gateway: istio-system/global-gateway
    consulHTTPAddr: consul.oman-fluxble-consul:8500
    dbname: envs       
  script:
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --debug --wait ./
