{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "APP.fullname" . }}-config
data:
{{- if .Values.configmap.configurationFiles }}
{{- range $key, $val := .Values.configmap.configurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
{{- if .Values.configmap.configurationEnv }}
{{- range $key, $val := .Values.configmap.configurationEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end -}}
{{- end -}}