#!/bin/bash

docker run --network host -p 80:80 \
    -e ENVS_HTTP_ADDR=http://127.0.0.1:9112 \
    - e MEERA_APP_OAUTH_HOST: '${env:// .ssoIssuer }' \
    - e MEERA_APP_OAUTH_CLIENT_ID: configurator \
    - e MEERA_APP_OAUTH_CLIENT_SECRET: DzXZxyDObSpsnR7qLqQ4p1LEVoIiE49e \
    - e MEERA_APP_OAUTH_CALLBACK_HOST: '${env:// .configuratorWebAddr }' \
    - e MEERA_APP_ENV_VAR_ME_TO: '${env:// .profileAddr }' \
    - e MEERA_APP_PRODUCT_APP_URL_CONFIGURATOR: '${env:// .configuratorAddr }' \
    - e MEERA_APP_PRODUCT_APP_URL_PROFILE: '${env:// .profileAddr }' \
    - e MEERA_APP_MEETING_URL: 'https://meeting.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_EDGE: 'https://edge.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_LANG: 'https://i18n.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_CRM: 'https://manager.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_WORKSPACE_URL: 'https://dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_BI_URL: 'https://bi.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_API: 'https://api.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_CADRE: 'https://profile.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_LICENSE: 'https://license.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_PLANNER: 'https://planner.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_HCM: 'https://hcm.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_OKR: 'https://okr.dev.meeraspace.com' \
    - e MEERA_APP_BASE_ENV_URL: 'https://dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_AMC: 'https://amc.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_ORGANIZATION: 'https://organization.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_MAP: 'https://map.dev.meeraspace.com/' \
    - e MEERA_APP_PRODUCT_APP_URL_PDO: 'https://pdo.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_REACH: 'https://reach.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_CSR: 'https://csr.dev.meeraspace.com/' \
    - e MEERA_APP_PRODUCT_APP_URL_TROVE: 'https://was.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_COMPANY: 'https://company.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_URL_PEOPLEANALYTICS: 'https://peopleanalytics.dev.meeraspace.com/' \
    - e MEERA_APP_PRODUCT_APP_URL_PSA: 'https://psa.dev.meeraspace.com' \
    - e MEERA_APP_PRODUCT_APP_URL_REGULATION: 'https://k-regulation.dev.meeraspace.com' \
    --rm --name configurator-fe registry.gitlab.com/target-digital-transformation/workspace-configurator-fe/release
