// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/store/store.go

// Package store is a generated GoMock package.
package store

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Set mocks base method
func (m *MockStore) Set(key Key, val interface{}) error {
	ret := m.ctrl.Call(m, "Set", key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockStoreMockRecorder) Set(key, val interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStore)(nil).Set), key, val)
}

// Get mocks base method
func (m *MockStore) Get(key Key) (interface{}, error) {
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockStoreMockRecorder) Get(key interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), key)
}

// GetNsValues mocks base method
func (m *MockStore) GetNsValues(namespace string) (KeyVals, error) {
	ret := m.ctrl.Call(m, "GetNsValues", namespace)
	ret0, _ := ret[0].(KeyVals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNsValues indicates an expected call of GetNsValues
func (mr *MockStoreMockRecorder) GetNsValues(namespace interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNsValues", reflect.TypeOf((*MockStore)(nil).GetNsValues), namespace)
}

// GetKindValues mocks base method
func (m *MockStore) GetKindValues(kind string) (KeyVals, error) {
	ret := m.ctrl.Call(m, "GetKindValues", kind)
	ret0, _ := ret[0].(KeyVals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKindValues indicates an expected call of GetKindValues
func (mr *MockStoreMockRecorder) GetKindValues(kind interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKindValues", reflect.TypeOf((*MockStore)(nil).GetKindValues), kind)
}

// GetNsKindValues mocks base method
func (m *MockStore) GetNsKindValues(namespace, kind string) (KeyVals, error) {
	ret := m.ctrl.Call(m, "GetNsKindValues", namespace, kind)
	ret0, _ := ret[0].(KeyVals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNsKindValues indicates an expected call of GetNsKindValues
func (mr *MockStoreMockRecorder) GetNsKindValues(namespace, kind interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNsKindValues", reflect.TypeOf((*MockStore)(nil).GetNsKindValues), namespace, kind)
}

// Delete mocks base method
func (m *MockStore) Delete(key Key) error {
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockStoreMockRecorder) Delete(key interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), key)
}

// Close mocks base method
func (m *MockStore) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}
