name: ci
on:
  push:
    branches:
      - main
  pull_request:

env:
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.21

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - name: Clone envs from gitlab
        run: |
          git clone https://gitlab-ci-token:${{ secrets.GITLAB_CR_PAT }}@gitlab.com/target-digital-transformation/environment-store.git .

      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
      #
      # - uses: goreleaser/goreleaser-action@v2
      #   with:
      #     version: latest
      #     args: --snapshot --rm-dist
